name: Build and deploy Node.js app to Azure Web App - CSPCHATBOT-WEBAPP-TST

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Zip application
        run: |
          zip -r app.zip . \
            -x ".git/*" \
            -x ".github/*" \
            -x "node_modules/.cache/*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BF452D2B93A04E31887C13FF4546947A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_636FEA39C8854E24A95B24AE1E0E6A73 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FE1B87C30EFB47338F3D0B6EB77EFC3C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: CSPCHATBOT-WEBAPP-TST
          slot-name: Production
          package: app.zip
